# Generated by Django 6.0 on 2025-12-19 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmapi', '0002_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=155)),
                ('phone', models.CharField(max_length=155)),
                ('email', models.CharField(max_length=155)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='vmapi.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
