# Generated by Django 6.0 on 2025-12-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmapi', '0003_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_volunteers', to='vmapi.assignment')),
                ('volunteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_assignments', to='vmapi.volunteer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assignment_id', 'volunteer_id'), name='Unique_Assignment_Volunteer')],
            },
        ),
    ]
